runtime: custom
env: flex

resources:
  cpu: 2
  memory_gb: 4.0

entrypoint: find ${VIRTUAL_ENV}/lib/python3.7/site-packages/streamlit -type f \( -iname \*.py -o -iname \*.js \) -print0 | xargs -0 sed -i 's/healthz/health-check/g' && streamlit run app.py --server.port 8080 --server.enableCORS=false

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1